### ISSUE TITLE
Advanced image metadata

### ISSUE THREAD

**Issue by denzp** [denzp/cargo-wharf#17]
Dockerfile statements:
``` Dockerfile
EXPOSE 80/tcp
LABEL version="1.0"
VOLUME /data
STOPSIGNAL SIGKILL
```

Should have equivalent cargo-wharf metadata:
```toml
[package.metadata.wharf.output]
expose = ["80/tcp"]
labels = { version = "1.0" }
volumes = ["/data"]
stop_signal = "SIGKILL"
```
